version: '3'
services:
  mysql-local:
    container_name: mysql-local
    hostname: mysql-local
    image: mysql:8.0.25
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: igti_demo
    
  
  